version: '3.8'
services:

  participa:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_volume:/nexo/staticfiles
      - media_volume:/nexo/mediafiles
    
volumes:
  media_volume:
  static_volume:
  redis_volume:
