version: '3.8'


x-app: &default-app
  build:
      context: .
      dockerfile: Dockerfile
  volumes:
      - static_volume:/participa/staticfiles
      - media_volume:/participa/mediafiles
      - .:/participa
  restart: always


services:

  participa:
    <<: *default-app

  tailwind:
    <<: *default-app
    tty: true


    
volumes:
  media_volume:
  static_volume:
  redis_volume:
