version: '3.8'
services:

  participa:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_volume:/participa/staticfiles
      - media_volume:/participa/mediafiles
      - .:/participa
    entrypoint: /entrypoint_dev.sh
    
volumes:
  media_volume:
  static_volume:
  redis_volume:
