# Generated by Django 5.0 on 2024-03-19 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affinity',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Affinity',
                'verbose_name_plural': 'Affinities',
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Instance',
                'verbose_name_plural': 'Instances',
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Territory',
                'verbose_name_plural': 'Territories',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('polis_id', models.CharField(max_length=200)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polis.instance')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('NB', 'Non-Binary'), ('TG', 'Transgender'), ('I', 'Intersex'), ('Q', 'Queer'), ('N', 'Prefer Not to Say'), ('O', 'Other')], max_length=2)),
                ('year_of_birth', models.IntegerField()),
                ('affinity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polis.affinity')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polis.instance')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polis.territory')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['instance', 'affinity'],
            },
        ),
    ]
