# Generated by Django 5.0 on 2024-03-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolisConversation",
            fields=[
                ("zid", models.BigIntegerField(primary_key=True, serialize=False)),
                ("topic", models.TextField()),
                ("description", models.TextField()),
                ("up_votes", models.IntegerField()),
                ("participant_count", models.IntegerField()),
                ("is_anon", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("is_public", models.BooleanField()),
            ],
            options={
                "db_table": "conversations",
                "managed": False,
            },
        ),
    ]
