# Generated by Django 5.0 on 2023-12-14 22:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
