# Generated by Django 5.0 on 2024-03-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="show_description",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="show_footer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conversation",
            name="show_help",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conversation",
            name="show_topic",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="subscribe_type",
            field=models.CharField(
                blank=True, choices=[("1", "Email")], max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="border",
            field=models.CharField(
                blank=True, default="1px solid #ccc", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="border_radius",
            field=models.CharField(
                blank=True, default="4px", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="height",
            field=models.CharField(
                blank=True, default="930", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="padding",
            field=models.CharField(
                blank=True, default="4px", max_length=200, null=True
            ),
        ),
    ]
