# Generated by Django 5.0 on 2024-03-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polis", "0002_conversation_auth_opt_allow_3rdparty_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={
                "ordering": ["id", "affinity"],
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
            },
        ),
        migrations.RemoveField(
            model_name="participant",
            name="instance",
        ),
        migrations.AddField(
            model_name="participant",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
