# Generated by Django 5.0 on 2024-03-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polis", "0002_conversation_show_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="bg_white",
            field=models.CharField(
                blank=True, default="#fff", max_length=200, null=True
            ),
        ),
    ]
