# Generated by Django 5.0 on 2023-12-14 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polis", "0002_alter_participant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="instance",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="polis.instance",
            ),
            preserve_default=False,
        ),
    ]
