# Generated by Django 5.0 on 2024-03-18 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polis", "0002_polisconversation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolisParticipant",
            fields=[
                ("pid", models.BigIntegerField(primary_key=True, serialize=False)),
                ("vote_count", models.IntegerField()),
                ("created", models.DateTimeField()),
                ("last_interaction", models.DateTimeField()),
            ],
            options={
                "db_table": "participants",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PolisUser",
            fields=[
                ("uid", models.BigIntegerField(primary_key=True, serialize=False)),
                ("hname", models.TextField()),
                ("email", models.TextField()),
                ("site_id", models.TextField()),
                ("site_owner", models.BooleanField()),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="affinity",
            options={"verbose_name": "Affinity", "verbose_name_plural": "Affinities"},
        ),
        migrations.AlterModelOptions(
            name="conversation",
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
            },
        ),
        migrations.AlterModelOptions(
            name="instance",
            options={"verbose_name": "Instance", "verbose_name_plural": "Instances"},
        ),
        migrations.AlterModelOptions(
            name="participant",
            options={
                "ordering": ["instance", "affinity"],
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
            },
        ),
        migrations.AlterModelOptions(
            name="territory",
            options={"verbose_name": "Territory", "verbose_name_plural": "Territories"},
        ),
        migrations.CreateModel(
            name="PolisXid",
            fields=[
                (
                    "uid",
                    models.BigIntegerField(
                        db_column="uid", primary_key=True, serialize=False
                    ),
                ),
                ("x_profile_image_url", models.TextField()),
                ("x_name", models.TextField()),
                ("x_email", models.TextField()),
                ("created", models.DateTimeField()),
                ("modified", models.DateTimeField()),
                (
                    "xid",
                    models.ForeignKey(
                        db_column="xid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polis.participant",
                    ),
                ),
            ],
        ),
    ]
