# Generated by Django 5.0 on 2024-03-22 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polis", "0003_alter_participant_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="affinity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polis.affinity",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("F", "Female"),
                    ("M", "Male"),
                    ("NB", "Non-Binary"),
                    ("TG", "Transgender"),
                    ("I", "Intersex"),
                    ("Q", "Queer"),
                    ("N", "Prefer Not to Say"),
                    ("O", "Other"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="territory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polis.territory",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="year_of_birth",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
