# Generated by Django 5.0 on 2024-03-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polis", "0003_alter_affinity_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolisPageId",
            fields=[
                ("zid", models.BigIntegerField(primary_key=True, serialize=False)),
                ("page_id", models.TextField()),
                ("site_id", models.TextField()),
            ],
            options={
                "db_table": "page_ids",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PolisReport",
            fields=[
                ("rid", models.BigIntegerField(primary_key=True, serialize=False)),
                ("report_id", models.TextField()),
            ],
            options={
                "db_table": "reports",
                "managed": False,
            },
        ),
    ]
