# Generated by Django 5.0 on 2024-03-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polis", "0003_alter_conversation_bg_white"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="bg_white",
            field=models.BooleanField(default=True),
        ),
    ]
