# Generated by Django 5.0 on 2024-03-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polis", "0004_alter_participant_affinity_alter_participant_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
