# Generated by Django 5.0 on 2024-08-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polis", "0005_participant_avatar_url_participant_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="nick_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nick Name"
            ),
        ),
    ]
