# Generated by Django 5.0 on 2024-08-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polis", "0006_participant_nick_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="color_primary",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Primary color"
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="color_secondary",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Secondary color"
            ),
        ),
    ]
