# Generated by Django 5.0 on 2024-08-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polis", "0007_conversation_color_primary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="border",
            field=models.CharField(
                blank=True,
                default="0px solid #ccc",
                max_length=200,
                null=True,
                verbose_name="Border",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="height",
            field=models.CharField(
                blank=True,
                default="400",
                max_length=200,
                null=True,
                verbose_name="Iframe Height",
            ),
        ),
    ]
