# Generated by Django 5.0 on 2024-09-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polis", "0008_alter_conversation_border_alter_conversation_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="show_in_list",
            field=models.BooleanField(default=False, verbose_name="Show in list"),
        ),
    ]
