# Generated by Django 5.0 on 2024-11-02 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polis", "0012_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_order", models.IntegerField()),
                ("link_text", models.CharField(max_length=200)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polis.conversation",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polis.page"
                    ),
                ),
            ],
        ),
    ]
