# Generated by Django 5.0 on 2024-11-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polis", "0013_conversationpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationpage",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
